    spring.application.name=demo
    spring.datasource.url=jdbc:postgresql://localhost:5433/Tasks
    spring.datasource.username=postgres
    spring.datasource.password=${DB_PASSWORD}

    spring.jpa.hibernate.ddl-auto=validate
    spring.jpa.open-in-view=false
    logging.level.org.hibernate.SQL=DEBUG
